FROM golang:1.19 as base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./

###

FROM base as develop

RUN CGO_ENABLED=0 GOOS=linux go build -o /crudie-go

EXPOSE 8080

CMD ["/crudie-go"]